connector_1:
	x: 0.0
	y: 0.0
	z: 0.0
	roll: 0.0
	pitch: 0.0
	yaw: 0.0
connector_2:
	x: 0.0
	y: 0.0
	z: 0.0
	roll: 0.0
	pitch: 0.0
	yaw: 0.0
connector_3:
	x: 0.0
	y: 0.0
	z: 0.0
	roll: 0.0
	pitch: 0.0
	yaw: 0.0
connector_4:
	x: 0.0
	y: 0.0
	z: 0.0
	roll: 0.0
	pitch: 0.0
	yaw: 0.0
connector_5:
	x: 0.0
	y: 0.0
	z: 0.0
	roll: 0.0
	pitch: 0.0
	yaw: 0.0
footprint:
	x: 0.0
	y: 0.0
	z: 0.0
	roll: 0.0
	pitch: 0.0
	yaw: 0.0
